
<RootWidget>:
    orientation: 'vertical'
    spacing: 10

<ServerWidget>:
    button_start: button_start
    button_stop: button_stop
    textinput_ip: textinput_ip
    textinput_port: textinput_port

    orientation: 'horizontal'

    Button:
        id: button_start
        text: 'Start Server'
        on_release: root.func_start()
    Button:
        id: button_stop
        text: 'Stop Server'
        on_release: root.func_stop()

    GridLayout:
        cols: 2

        Label:
            text: 'IP'
        TextInput:
            id: textinput_ip
            text: '127.0.0.1'
        Label:
            text: 'Port'
        TextInput:
            id: textinput_port
            text: '7000'

<ConfigWidget>:
    button_load_preprocess: button_load_preprocess
    button_load_control: button_load_control
    button_load_keymap: button_load_keymap
    textinput_preprocess: textinput_preprocess
    textinput_control: textinput_control
    textinput_keymap: textinput_keymap

    cols: 2

    TextInput:
        id: textinput_preprocess
    Button:
        id: button_load_preprocess
        text: 'Load Preprocess'
        on_release: root.ShowLoadDialog(textinput_preprocess)
    TextInput:
        id: textinput_control
    Button:
        id: button_load_control
        text: 'Load Control'
        on_release: root.ShowLoadDialog(textinput_control)
    TextInput:
        id: textinput_keymap
    Button:
        id: button_load_keymap
        text: 'Load Keymap'
        on_release: root.ShowLoadDialog(textinput_keymap)

<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: 'vertical'

        FileChooserListView:
            id: filechooser

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: 'Cancel'
                on_release: root.func_cancel()

            Button:
                text: 'Load'
                on_release: root.func_load(filechooser.path, filechooser.selection, root.textinput_update)